name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Decode keystore file
        uses: timheuer/base64-to-file@v1
        id: findroid_keystore
        with:
          fileName: 'findroid-keystore.jks'
          encodedString: ${{ secrets.FINDROID_KEYSTORE }}

      - name: Build and sign phone APKs
        run: ./gradlew assembleRelease

      - name: Build and sign TV APKs
        run: ./gradlew :tv:assembleRelease

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            ./app/phone/build/outputs/apk/libre/release/findroid-${{ github.ref_name }}-libre-arm64-v8a.apk
            ./app/phone/build/outputs/apk/libre/release/findroid-${{ github.ref_name }}-libre-armeabi-v7a.apk
            ./app/phone/build/outputs/apk/libre/release/findroid-${{ github.ref_name }}-libre-x86_64.apk
            ./app/phone/build/outputs/apk/libre/release/findroid-${{ github.ref_name }}-libre-x86.apk
            ./app/tv/build/outputs/apk/libre/release/findroid-${{ github.ref_name }}-libre-arm64-v8a.apk
            ./app/tv/build/outputs/apk/libre/release/findroid-${{ github.ref_name }}-libre-armeabi-v7a.apk
            ./app/tv/build/outputs/apk/libre/release/findroid-${{ github.ref_name }}-libre-x86_64.apk
            ./app/tv/build/outputs/apk/libre/release/findroid-${{ github.ref_name }}-libre-x86.apk
